### ISSUE TITLE
Compatible/update to Alpine V3

### ISSUE THREAD

**Issue by austriker27** [markusantonwolf/ta-gallery#11]
Hello! 

I know alpine v3 is super new, but any plans on updating to it? 

Thanks!

**Comment by markusantonwolf** [comment]
@austriker27 I already started the "transformation" with TA-YouTube and TA-Gallery is on the list - so stay tuned :-)

**Comment by markusantonwolf** [comment]
@austriker27 wasn't a big issue - so to use TA-Gallery with Alpine.js version 3 you can use the following script after updating to TA-Gallery version 2.1.0: 

`https://unpkg.com/@markusantonwolf/ta-gallery@2.1.0/dist/js/ta-gallery-next.min.js`

or copy it from the repo:

`./node_modules/@markusantonwolf/ta-gallery/src/scripts/ta-gallery-next.js`

FYI: Version 3.0 of TA-Gallery will skip support for Alpine.js version 2.x
