### ISSUE TITLE
ReferenceError: ta_gallery_safelist is not defined

### ISSUE THREAD

**Issue by martin-ro** [markusantonwolf/ta-gallery#13]
I have installed the plugin and configure tailwind but get this error `ReferenceError: ta_gallery_safelist is not defined`.

This is my `tailwind.config.js`:

```js
purge: {
        content: [
            './resources/**/*.blade.php',
            './resources/**/*.js',
            './resources/**/*.vue',
            './resources/**/*.svg',
        ],
        options: {
            safelist: [...ta_gallery_safelist],
        },
    },
```

Any idea what I'm doing wrong here?

**Comment by markusantonwolf** [comment]
@martin-ro thanks for your feedback.

https://ta-styled-plugins.com/ta-gallery/tailwind-css-plugin/#purge-css-with-tailwind-css

On this page you can find in the first row:

`const ta_gallery_safelist = require('./node_modules/@markusantonwolf/ta-gallery/src/plugin/safelist');`

This will help 😄

**Comment by martin-ro** [comment]
Ahhh! Sorry, didn't catch that! Works now.

Thank you!
