### ISSUE TITLE
Uncaught ReferenceError: hide is not defined

### ISSUE THREAD

**Issue by rajatpatelz** [markusantonwolf/ta-gallery#19]
> Uncaught ReferenceError: hide is not defined 

getting this error when livewire component get updated

https://github.com/markusantonwolf/ta-gallery/blob/eb674da51956c061b8b213dbaa3e83879a7c6ed7/src/scripts/ta-gallery-next.js#L167

instead of 
`show : hide`
It should be
`show : false`

**Comment by markusantonwolf** [comment]
I will take a look at it later this day :-) 
You might be right...
