### ISSUE TITLE
Webpack does not include taGallery

### ISSUE THREAD

**Issue by Jako** [markusantonwolf/ta-gallery#20]
I had to add ta-gallery in an existing project and the build process does not include the taGallery script for whatever reason.

I had to add the following lines to the main.js file to make the script work:

```
// Import taGallery
/* eslint-disable no-unused-vars */
import taGallery from '@markusantonwolf/ta-gallery/dist/js/ta-gallery-next';
/* eslint-enable no-unused-vars */
```

adding `require('@markusantonwolf/ta-gallery')` to the plugin section in tailwind.config.js was not enough.

Tailwind 3, Webpack 4

**Comment by markusantonwolf** [comment]
Thank you very much - I will add this to the documentation...

**Comment by markusantonwolf** [comment]
https://ta-styled-plugins.com/ta-gallery/getting-started/#webpack-4-and-tailwind-3--issue--fix
