### ISSUE TITLE
Problems when building a project in the production mode

### ISSUE THREAD

**Issue by sung1asses** [markusantonwolf/ta-gallery#8]
I use Laravel 8, tailwind css, npm.
When I build a project in dev mode, everything is fine. When I build a project in production mode, the following error appears:
[Error: ENOENT: no such file or directory, open './src/styles/ta-gallery.css'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './src/styles/ta-gallery.css'
}
![image](https://user-images.githubusercontent.com/50788522/119267799-e9541600-bc11-11eb-8fda-9e1d3a386da9.png)

**Comment by markusantonwolf** [comment]
@sung1asses issue should be removed in version 2.0.3 - please update to 2.0.3

**Comment by markusantonwolf** [comment]
The issue should no longer appear...
